# Generated by Django 2.2.5 on 2020-04-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearnerapp', '0018_auto_20200428_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='ques',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
